services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: node
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  db-data:
  redis-data:

networks:
  app-network:
    driver: bridge